# -*- coding: utf-8 -*-
"""4_Hill Climbing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/178e4tLuXeRg6_9exc1A5UROs07K6QXdT
"""

def hillClimbing(func, start, step = 0.01, num_iter = 2000):
    cp, cv = start, func(start)
    for _ in range(num_iter):
        npp = cp + step
        nvp = func(npp)

        npn = cp - step
        nvn = func(npn)

        if(nvp > cv and nvp >= nvn):
            cp = npp
            cv = nvp
        elif(nvn > cv and nvn > nvp):
            cp = npn
            cv = nvn
        else:
            break
    return cp, cv

func_str = input('Enter a function')
func = lambda x: eval(func_str)
v = float(input('Enter a starting value'))
pos, val = hillClimbing(func, v)
print('Maxima:', pos)
print('Max value: ', val)