# -*- coding: utf-8 -*-
"""8_K-means.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rHF1JhL87cxdZeEChud8PfPslC4bFlOI
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

X = load_iris().data

def kmeans(X, k):
    centroids = X[np.random.choice(X.shape[0], k, replace=False)]
    for _ in range(100):
        dist = np.linalg.norm(X[:, None] - centroids, axis=2)
        labels = np.argmin(dist, axis=1)
        centroids = np.array([X[labels == i].mean(axis=0) for i in range(k)])
    return centroids, labels

centroids, labels = kmeans(X, 3)
colors = ['r', 'g', 'b']
for i in range(3):
    plt.scatter(X[labels == i, 0], X[labels == i, 1], c=colors[i])
plt.scatter(centroids[:, 0], centroids[:, 1], marker='x', c='black')
plt.title('K-Means Clustering')
plt.xlabel('Sepal Width')
plt.ylabel('Sepal Length')